/* /client-access — per-client magic link redemption.
 *
 * Reachable with NO session (the token itself is the credential — generated by
 * internal staff in Config → Client Access Links, see functions/api/client-links).
 * A valid, unrevoked token issues a normal client session (same cookie the
 * password-based /quote-login would) and sends the browser into the quote tool.
 * Listed as an OPEN_PATH in _middleware.js so the request reaches this handler.
 */
import { makeToken, clientCookie, AUD_CLIENT } from './_shared.js';

export async function onRequestGet({ request, env }) {
  const url = new URL(request.url);
  const token = url.searchParams.get('token') || '';
  const row = token
    ? await env.DB.prepare('SELECT id FROM client_links WHERE token = ? AND revoked = 0').bind(token).first()
    : null;
  if (row) {
    const sessionToken = await makeToken(env.SESSION_SECRET, AUD_CLIENT);
    return new Response(null, { status: 302, headers: { Location: '/quote', 'Set-Cookie': clientCookie(request, sessionToken) } });
  }
  // Unknown / revoked token — fall back to the manual client login.
  return Response.redirect(`${url.origin}/quote-login`, 302);
}
